-- Persistent users, browser sessions, credits, payments, usage, and translation jobs.
-- UUID values are generated by the Node.js application, so no PostgreSQL extension is required.

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    email TEXT UNIQUE,
    password_hash TEXT,
    credits_balance INTEGER NOT NULL DEFAULT 0 CHECK (credits_balance >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Anonymous users have no email until registration is implemented.
ALTER TABLE users ALTER COLUMN email DROP NOT NULL;

CREATE TABLE IF NOT EXISTS user_sessions (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payments (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    provider TEXT NOT NULL,
    provider_payment_id TEXT NOT NULL,
    amount_cents INTEGER NOT NULL CHECK (amount_cents >= 0),
    currency TEXT NOT NULL,
    credits_granted INTEGER NOT NULL CHECK (credits_granted >= 0),
    status TEXT NOT NULL,
    idempotency_key TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(provider, provider_payment_id)
);

CREATE TABLE IF NOT EXISTS credit_ledger (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    delta INTEGER NOT NULL CHECK (delta <> 0),
    balance_after INTEGER NOT NULL CHECK (balance_after >= 0),
    reason TEXT NOT NULL,
    reference_type TEXT,
    reference_id UUID,
    idempotency_key TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS usage_events (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES users(id),
    ip_hash TEXT,
    event_type TEXT NOT NULL,
    query_hash TEXT,
    credits_charged INTEGER NOT NULL DEFAULT 0 CHECK (credits_charged >= 0),
    cache_hit BOOLEAN NOT NULL DEFAULT FALSE,
    provider TEXT,
    model TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS translation_jobs (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    source_site TEXT NOT NULL,
    manga_id TEXT NOT NULL,
    chapter_id TEXT NOT NULL,
    status TEXT NOT NULL,
    credits_reserved INTEGER NOT NULL DEFAULT 0 CHECK (credits_reserved >= 0),
    credits_charged INTEGER NOT NULL DEFAULT 0 CHECK (credits_charged >= 0),
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS user_sessions_user_idx
    ON user_sessions(user_id);

CREATE INDEX IF NOT EXISTS user_sessions_expires_idx
    ON user_sessions(expires_at);

CREATE INDEX IF NOT EXISTS credit_ledger_user_created_idx
    ON credit_ledger(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS usage_events_user_created_idx
    ON usage_events(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS usage_events_ip_created_idx
    ON usage_events(ip_hash, created_at DESC);

CREATE INDEX IF NOT EXISTS translation_jobs_user_created_idx
    ON translation_jobs(user_id, created_at DESC);
